=== Scenario 1
Amount of opponents: 3 +
Difficulty level: 1 +
Description: Free kick far from the goal with two defenders and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s01.json[]
----

image::scenarios-challenge-1/scenario1.svg[Interactive,700,opts=interactive]

=== Scenario 2
Amount of opponents: 3 +
Difficulty level: 1 +
Description: Free kick on the middle line with two defenders and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s02.json[]
----

image::scenarios-challenge-1/scenario2.svg[Interactive,700,opts=interactive]

=== Scenario 3
Amount of opponents: 4 +
Difficulty level: 1 +
Description: Free kick from the center of the field with three opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s03.json[]
----

image::scenarios-challenge-1/scenario3.svg[Interactive,700,opts=interactive]

=== Scenario 4
Amount of opponents: 4 +
Difficulty level: 2 +
Description: Free kick from the middle line with three opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s04.json[]
----

image::scenarios-challenge-1/scenario4.svg[Interactive,700,opts=interactive]

=== Scenario 5
Amount of opponents: 5 +
Difficulty level: 3 +
Description: Free kick from the top-left part of the field with 4 opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s05.json[]
----

image::scenarios-challenge-1/scenario5.svg[Interactive,700,opts=interactive]

=== Scenario 6
Amount of opponents: 5 +
Difficulty level: 2 +
Description: Free kick from the bottom-right part of the field with four opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s06.json[]
----

image::scenarios-challenge-1/scenario6.svg[Interactive,700,opts=interactive]

=== Scenario 7
Amount of opponents: 5 +
Difficulty level: 3 +
Description: Free kick from the bottom-left part of the field with four opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s07.json[]
----

image::scenarios-challenge-1/scenario7.svg[Interactive,700,opts=interactive]

=== Scenario 8
Amount of opponents: 6 +
Difficulty level: 3 +
Description: Free kick from the top-right corner with five opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s08.json[]
----

image::scenarios-challenge-1/scenario8.svg[Interactive,700,opts=interactive]

=== Scenario 9
Amount of opponents: 6 +
Difficulty level: 3 +
Description: Free kick from the bottom-left part of the field with five opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s09.json[]
----

image::scenarios-challenge-1/scenario9.svg[Interactive,700,opts=interactive]

=== Scenario 10
Amount of opponents: 6 +
Difficulty level: 2 +
Description: Free kick from within the field with five opponents and a goalkeeper. +

[source,json]
----
include::scenarios-challenge-1/hwc1s10.json[]
----

image::scenarios-challenge-1/scenario10.svg[Interactive,700,opts=interactive]
